apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: genparker-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: andy2greatu2@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx
